### ISSUE TITLE
TypeError: GasTracker is not a constructor

### ISSUE THREAD

**Issue by ko0f** [d3or/hardhat-gas-trackooor#2]
I can't seem to find how to access `GasTracker`.

The docs only mention to use 
```
require("hardhat-gas-trackooor");
```
but that doesn't define `GasTracker`, so looking at the package source code it extends `hre` 
```
extendEnvironment((hre: HardhatRuntimeEnvironment) => {
  hre.GasTracker = GasTracker;
  hre.GetGas = GetGas;
});
```
so I tried 
```
require("hardhat-gas-trackooor");
const hre = require("hardhat");
...
test = new hre.GasTracker(await Test.deploy());
```
but when executed using `npx hardhat test` it throws `TypeError: GasTracker is not a constructor` and `hre.GasTracker` is undefined.

Also tried switching the require lines so that `require("hardhat-gas-trackooor");` is after `const hre = require("hardhat");` but it didn't help.

**Comment by d3or** [comment]
You need to add `require("hardhat-gas-trackooor")`  inside your `hardhat.config.ts`, this will expose the GasTracker to the hardhat runtime environment and be accessible anywhere hardhat is required.
