### ISSUE TITLE
Add leading spaces to output

### ISSUE THREAD

**Issue by ko0f** [d3or/hardhat-gas-trackooor#3]
UI suggestion - add 5 leading spaces to the output string and change the red box to a green battery.

Adding spacing will fix indentation of output to align with the test hierarchy.

Red fuel station looks alarming, changing to a relaxed green battery would look better.

Instead of 
```
      console.log(
        '\x1b' + gasColor,
        `⛽ ${prop} (${gas} gas) ${gas === 69420 ? 'nice.' : ''}`,
      );
```
<img width="208" alt="Screen Shot 2022-06-10 at 11 44 35" src="https://user-images.githubusercontent.com/6340033/173031343-961e5bde-aea1-47d2-bce3-2d03e9005ca7.png">

change to -
```
      console.log(
        '\x1b' + gasColor,
        `     🔋 ${prop} (${gas} gas) ${gas === 69420 ? 'nice.' : ''}`,
      );
```
<img width="249" alt="Screen Shot 2022-06-10 at 11 44 54" src="https://user-images.githubusercontent.com/6340033/173031385-dc615186-2378-4e4e-bb67-4c4833a8e8d1.png">

**Comment by ko0f** [comment]
You can also change to an empty battery if gas is high 🪫

**Comment by ko0f** [comment]
Try to find the number of indentation from hardhat's plugin API, as it's possible to have more indentation if describe within describe is used.

Ideally `spaceCount = indentLevels * 2 + 1` assuming each `describe` and each `it` is creates an indentation level.

**Comment by ko0f** [comment]
BTW nice backdoor :)

**Comment by d3or** [comment]
Do you mind opening up a pull request with the changes? I can merge it in :D

**Comment by ko0f** [comment]
Created https://github.com/d3or/hardhat-gas-trackooor/pull/4

Made further adjustments until got to a design I liked, feel free to change.

<img width="286" alt="Screen Shot 2022-06-11 at 11 59 47" src="https://user-images.githubusercontent.com/6340033/173181398-c554d477-75c0-41b4-92b0-49db3dbc21a9.png">

**Comment by d3or** [comment]
Just merged it, thanks!
